kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-producer-config
data:
  kafkaHost: {{ .Values.kafka.bootstrapServers | quote }}
  username: {{ .Values.kafka.username | quote }}
  topic: {{ .Values.kafka.topic | quote }}
  password: {{ .Values.kafka.password | quote }}
  mechanism: {{ .Values.kafka.mechanism | quote }}
  batchTimeout: {{ .Values.kafka.batchTimeout | quote }}
  maxBatchSize: {{ .Values.kafka.maxBatchSize | quote }}